# Métricas de avaliação de desempenho dos modelos
METRICS: ["smape", "rmsle", "owa"]

# Métrica principal para avaliar o desempenho dos modelos
KEY_METRIC: "owa"

# Quantidade de dados para teste
TEST_SIZE: 30

# Quantidade de folds para validação cruzada
CV_FOLDS: 4

# Comprimento do passo para gerar os folds da validação cruzada
CV_STEP_LENGTH: 30

# Possibilidades de sazonalidades mensais para as séries temporais
SEASONALITIES: [30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330, 360]

# Número de experimentos do Optuna
OPTUNA_TRIALS: 30