# Métricas de avaliação de desempenho dos modelos
METRICS: ["smape", "rmsle", "owa"]

# Métrica principal para avaliar o desempenho dos modelos
KEY_METRIC: "owa"

# Quantidade de dados para teste
TEST_SIZE: 30

# Quantidade de folds para validação cruzada
CV_FOLDS: 4

# Comprimento do passo para gerar os folds da validação cruzada
CV_STEP_LENGTH: 30

# Possibilidades de tamanho de janela da Média Móvel Simples
SMA_WINDOWS: [7, 14, 30, 60, 90, 120, 180, 365]